import React, { useState } from 'react';
import JSZip from 'jszip';
import { ExportItem, ManifestConfig } from '../types';
import { formatBytes } from '../utils/imageProcess';
import { Download, PackageCheck, CheckSquare, Square, FileArchive, Sparkles, Image as ImageIcon } from 'lucide-react';

interface ExportPanelProps {
  exportItems: ExportItem[];
  manifestConfig: ManifestConfig;
  onToggleItem: (id: string) => void;
  onToggleSelectAll: (selectAll: boolean) => void;
}

export const ExportPanel: React.FC<ExportPanelProps> = ({
  exportItems,
  manifestConfig,
  onToggleItem,
  onToggleSelectAll,
}) => {
  const [isZipping, setIsZipping] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const selectedItems = exportItems.filter((item) => item.selected);
  const allSelected = exportItems.length > 0 && selectedItems.length === exportItems.length;

  const totalBytes = selectedItems.reduce((sum, item) => sum + item.fileSizeBytes, 0);

  // Generate & Download ZIP bundle
  const handleDownloadZip = async () => {
    if (selectedItems.length === 0) return;

    setIsZipping(true);
    setDownloadSuccess(false);

    try {
      const zip = new JSZip();

      // 1. Add generated image files into ZIP
      for (const item of selectedItems) {
        if (item.blob) {
          zip.file(item.spec.filename, item.blob);
        }
      }

      // 2. Add manifest.webmanifest to ZIP
      const manifestObject = {
        name: manifestConfig.name || 'PWA App',
        short_name: manifestConfig.shortName || 'PWA',
        description: manifestConfig.description,
        theme_color: manifestConfig.themeColor,
        background_color: manifestConfig.backgroundColor,
        display: manifestConfig.display,
        start_url: manifestConfig.startUrl,
        scope: manifestConfig.scope,
        icons: selectedItems.map((item) => ({
          src: item.spec.filename,
          sizes: `${item.spec.width}x${item.spec.height}`,
          type: 'image/png',
          purpose: item.spec.purpose,
        })),
      };

      zip.file('manifest.webmanifest', JSON.stringify(manifestObject, null, 2));

      // 3. Add HTML Head tags snippet file
      const htmlSnippet = `<!-- PWA Head Snippet for ${manifestConfig.name} -->
<link rel="manifest" href="/manifest.webmanifest" />
<meta name="theme-color" content="${manifestConfig.themeColor}" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
`;
      zip.file('pwa-head-snippet.html', htmlSnippet);

      // 4. Add README
      const readmeText = `================================================
  PWA Icons Bundle generated by PWA 圖示產生器
================================================

資料夾包含檔案：
1. pwa-192x192.png (purpose: "any")
2. pwa-512x512.png (purpose: "any")
3. pwa-maskable-192x192.png (purpose: "maskable")
4. pwa-maskable-512x512.png (purpose: "maskable")
5. apple-touch-icon.png (180x180)
6. favicon-32x32.png & favicon-16x16.png
7. manifest.webmanifest
8. pwa-head-snippet.html

部署提示：
請將上述圖片與 manifest.webmanifest 放置於 Web 伺服器 public 根目錄，並將 pwa-head-snippet.html 內文貼入 HTML <head>。
`;
      zip.file('README.txt', readmeText);

      // Generate zip blob
      const zipBlob = await zip.generateAsync({ type: 'blob' });

      // Create download trigger
      const url = URL.createObjectURL(zipBlob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `pwa-icons-bundle-${Date.now()}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 4000);
    } catch (err) {
      console.error('Packaging zip failed:', err);
    } finally {
      setIsZipping(false);
    }
  };

  const handleDownloadSingle = (item: ExportItem) => {
    if (!item.dataUrl) return;
    const link = document.createElement('a');
    link.href = item.dataUrl;
    link.download = item.spec.filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="rounded-2xl border border-white/10 bg-[#141415] p-5 shadow-2xl space-y-4 min-w-0 w-full overflow-hidden">
      {/* Header & Main Download Action */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 border-b border-white/10 pb-4 min-w-0 w-full">
        <div>
          <div className="flex items-center gap-2">
            <PackageCheck className="h-5 w-5 text-blue-500" />
            <h3 className="text-sm sm:text-base font-semibold text-white uppercase tracking-tight">圖示與打包下載中心</h3>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            已選取 <strong className="text-blue-400">{selectedItems.length}</strong> / {exportItems.length} 個圖示檔
            （預估大小: {formatBytes(totalBytes)}）
          </p>
        </div>

        <button
          onClick={handleDownloadZip}
          disabled={isZipping || selectedItems.length === 0}
          className={`flex items-center gap-2 rounded-xl px-5 py-2.5 text-xs font-bold text-white shadow-lg transition-all duration-200 shrink-0 ${
            downloadSuccess
              ? 'bg-emerald-600 shadow-emerald-600/30'
              : 'bg-blue-600 hover:bg-blue-500 hover:scale-[1.02] active:scale-[0.98] shadow-blue-500/20'
          } disabled:opacity-50 disabled:cursor-not-allowed`}
        >
          {isZipping ? (
            <>
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
              打包中 (JSZip)...
            </>
          ) : downloadSuccess ? (
            <>
              <Sparkles className="h-4 w-4 animate-bounce" />
              已完成下載 ZIP 檔案！
            </>
          ) : (
            <>
              <Download className="h-4 w-4" />
              一鍵下載 Bundle Zip File
            </>
          )}
        </button>
      </div>

      {/* Select All Toggle Bar */}
      <div className="flex items-center justify-between text-xs text-slate-400">
        <button
          onClick={() => onToggleSelectAll(!allSelected)}
          className="flex items-center gap-1.5 font-medium hover:text-white transition-colors"
        >
          {allSelected ? (
            <CheckSquare className="h-4 w-4 text-blue-400" />
          ) : (
            <Square className="h-4 w-4 text-slate-500" />
          )}
          全選 / 取消全選
        </button>

        <span className="text-[11px] text-slate-500">
          包含 192x192, 512x512, Maskable, Apple Touch Icon & Favicons
        </span>
      </div>

      {/* Grid of Generated Icons */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
        {exportItems.map((item) => {
          const isMaskable = item.spec.purpose === 'maskable';

          return (
            <div
              key={item.spec.id}
              onClick={() => onToggleItem(item.spec.id)}
              className={`group relative flex flex-col justify-between rounded-xl border p-3 cursor-pointer transition-all min-w-0 ${
                item.selected
                  ? 'border-blue-500/60 bg-blue-950/30 ring-1 ring-blue-500/30'
                  : 'border-white/10 bg-[#0A0A0B] opacity-60 hover:opacity-100'
              }`}
            >
              {/* Checkbox Header */}
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-1.5 min-w-0">
                  <div
                    className={`h-4 w-4 rounded flex items-center justify-center shrink-0 ${
                      item.selected ? 'bg-blue-600 text-white' : 'border border-white/10 bg-[#141415]'
                    }`}
                  >
                    {item.selected && <CheckSquare className="h-3 w-3" />}
                  </div>
                  <span className="truncate text-xs font-semibold text-slate-200">{item.spec.label}</span>
                </div>

                {item.spec.isRequiredForPWA && (
                  <span className="rounded bg-blue-500/10 px-1.5 py-0.5 text-[9px] font-mono text-blue-400 border border-blue-500/20 shrink-0">
                    必備
                  </span>
                )}
              </div>

              {/* Icon Image Thumbnail */}
              <div className="my-3 flex h-20 items-center justify-center">
                <div
                  className={`relative flex h-16 w-16 items-center justify-center overflow-hidden shadow-md transition-transform group-hover:scale-105 ${
                    isMaskable
                      ? 'rounded-full ring-2 ring-blue-500/40 bg-[#141415]'
                      : 'rounded-xl ring-1 ring-white/10 bg-[#141415]'
                  }`}
                >
                  {item.dataUrl ? (
                    <img src={item.dataUrl} alt={item.spec.label} className="h-full w-full object-contain" />
                  ) : (
                    <ImageIcon className="h-6 w-6 text-slate-600" />
                  )}
                </div>
              </div>

              {/* Footer Specs & Download Single Button */}
              <div className="flex items-center justify-between border-t border-white/10 pt-2 text-[10px] text-slate-400 font-mono">
                <div>
                  <p>{item.dimensionsText}</p>
                  <p className="text-slate-500">{formatBytes(item.fileSizeBytes)}</p>
                </div>

                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDownloadSingle(item);
                  }}
                  className="rounded p-1 text-slate-400 hover:bg-white/10 hover:text-white transition-colors"
                  title="單獨下載 PNG"
                >
                  <Download className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
